name: tox

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [2.7, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install tox

    - name: Run Windows Test
      if: runner.os == 'Windows'
      run: |
        python -m tox -c python/tox_windows.ini

    - name: Run Linux Test
      if: runner.os != 'Linux'
      run: |
        cd $GITHUB_WORKSPACE/python
        tox -e py

    - name: Run MacOS Test
      if: runner.os != 'macOS'
      run: |
        cd $GITHUB_WORKSPACE/python
        tox -e py
